### ISSUE TITLE
Peer To peer review

### ISSUE THREAD

**Issue by NabilHY** [Benmuiruri/my-portfolio#13]
[on your Update layout branch] (https://github.com/Benmuiruri/my-portfolio/pull/11/commits/584b94b8a583aa97b72ef2de48145e2bb8eac97e#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R125-R128)
-Try only using anchor tags inside list items, kindly remove the span tag from the list tag .

**Comment by Benmuiruri** [comment]
Hi @NabilHY thanks for raising this issue. I removed the `span` elements in this [commit](https://github.com/Benmuiruri/my-portfolio/pull/15/commits/716345b8f8b9e8abe5145778db64af6e86a37042).
